name: helloworld shell commands

on: [push, pull_request]

jobs: 
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "helloworld github actions"
      - name: multiline string
        run: |
          node -v
          npm -v
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python

  runs-windows-commands:
    runs-on: windows-latest
    steps: 
      - name: Directory Powershell
        run: Get-Location
      - name: Directory bash
        run: pwd
        shell: bash