name: helloworld shell commands

on: [push, pull_request]

jobs: 
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "helloworld github actions"
      - name: multiline string
        run: |
          node -v
          npm -v
